### ISSUE TITLE
Twitter link is incorrect

### ISSUE THREAD

**Issue by domfarolino** [TimothyGu/timothygu.github.io#1]
Went on your website and noticed the Twitter social link pointed to a username with [one](https://github.com/TimothyGu/timothygu.github.io/blob/master/_config.yml#L26)-too-many underscores :)

**Comment by TimothyGu** [comment]
Ah, right. https://twitter.com/timothy_gu/status/952817469822922756

Thanks! Seems like I’m probably going to have to change all the other places to the correct user name now.

**Comment by TimothyGu** [comment]
Fixed in https://github.com/TimothyGu/timothygu.github.io/commit/2f243115c56ebb9e4c38226040dde56ebd1664de.
